//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAsDriverTraining.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyAsDriverTraining.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retry!.
        /// </summary>
        internal static string _Please_retry_ {
            get {
                return ResourceManager.GetString("_Please_retry_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string _System_Error {
            get {
                return ResourceManager.GetString("_System_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running!.
        /// </summary>
        internal static string Application_is_already_running_ {
            get {
                return ResourceManager.GetString("Application_is_already_running_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running!.
        /// </summary>
        internal static string Application_running {
            get {
                return ResourceManager.GetString("Application_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  are not setup!.
        /// </summary>
        internal static string are_not_setup {
            get {
                return ResourceManager.GetString("are_not_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_exit_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an incorrect Username or password. Authorsiation failed!.
        /// </summary>
        internal static string Authorsiation_failed_ {
            get {
                return ResourceManager.GetString("Authorsiation_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Done!.
        /// </summary>
        internal static string Backup_Done {
            get {
                return ResourceManager.GetString("Backup_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect to Database!.
        /// </summary>
        internal static string Cannot_Connect_to_Database_ {
            get {
                return ResourceManager.GetString("Cannot_Connect_to_Database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a customer with transaction!.
        /// </summary>
        internal static string Cannot_delete_a_customer_with_transaction_ {
            get {
                return ResourceManager.GetString("Cannot_delete_a_customer_with_transaction_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate path .
        /// </summary>
        internal static string Cannot_locate_path_ {
            get {
                return ResourceManager.GetString("Cannot_locate_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace Part No.!.
        /// </summary>
        internal static string Cannot_replace_Part_No__ {
            get {
                return ResourceManager.GetString("Cannot_replace_Part_No__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save data!.
        /// </summary>
        internal static string Cannot_save_data_ {
            get {
                return ResourceManager.GetString("Cannot_save_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category : .
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category do not exist! Do you wish to create new Category?.
        /// </summary>
        internal static string Category_do_not_exist__Do_you_wish_to_create_new_Category_ {
            get {
                return ResourceManager.GetString("Category_do_not_exist__Do_you_wish_to_create_new_Category_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was imported form CI cannot be changed!.
        /// </summary>
        internal static string CI_cannot_be_changed_ {
            get {
                return ResourceManager.GetString("CI_cannot_be_changed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        internal static string Confirm_exit {
            get {
                return ResourceManager.GetString("Confirm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confrim.
        /// </summary>
        internal static string Confrim {
            get {
                return ResourceManager.GetString("Confrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed!.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Success!.
        /// </summary>
        internal static string Connection_Success {
            get {
                return ResourceManager.GetString("Connection_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot be empty!.
        /// </summary>
        internal static string Country_cannot_be_empty {
            get {
                return ResourceManager.GetString("Country_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted.
        /// </summary>
        internal static string Data_Deleted {
            get {
                return ResourceManager.GetString("Data_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exported!.
        /// </summary>
        internal static string Data_Exported {
            get {
                return ResourceManager.GetString("Data_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exported!.
        /// </summary>
        internal static string Data_Exported_ {
            get {
                return ResourceManager.GetString("Data_Exported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Database cannot be connected! Would you like to switch to the local database?.
        /// </summary>
        internal static string Database_cannot_be_connected {
            get {
                return ResourceManager.GetString("Database_cannot_be_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cannot be empty.
        /// </summary>
        internal static string Database_cannot_be_empty {
            get {
                return ResourceManager.GetString("Database_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Setup.
        /// </summary>
        internal static string Database_Setup {
            get {
                return ResourceManager.GetString("Database_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From should be eailer than Date To!.
        /// </summary>
        internal static string Date_From_should_be_eailer_than_Date_To {
            get {
                return ResourceManager.GetString("Date_From_should_be_eailer_than_Date_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string Delete_Confirmation {
            get {
                return ResourceManager.GetString("Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed!.
        /// </summary>
        internal static string Delete_Failed_ {
            get {
                return ResourceManager.GetString("Delete_Failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 1 : .
        /// </summary>
        internal static string Description_1 {
            get {
                return ResourceManager.GetString("Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 2 : .
        /// </summary>
        internal static string Description_2 {
            get {
                return ResourceManager.GetString("Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this record.
        /// </summary>
        internal static string Do_you_want_to_delete_this_record {
            get {
                return ResourceManager.GetString("Do_you_want_to_delete_this_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to changed the customer?.
        /// </summary>
        internal static string Do_you_wish_to_changed_the_customer {
            get {
                return ResourceManager.GetString("Do_you_wish_to_changed_the_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO Term do not exist! Do you wish to create new DO Term?.
        /// </summary>
        internal static string Do_you_wish_to_create_new_DO_Term {
            get {
                return ResourceManager.GetString("Do_you_wish_to_create_new_DO_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Part No..
        /// </summary>
        internal static string Duplicated_Part_No_ {
            get {
                return ResourceManager.GetString("Duplicated_Part_No_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Part No.! Do you wish to continue?.
        /// </summary>
        internal static string Duplicated_Part_No___Do_you_wish_to_continue_ {
            get {
                return ResourceManager.GetString("Duplicated_Part_No___Do_you_wish_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EDIT.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving!.
        /// </summary>
        internal static string Error_Saving_ {
            get {
                return ResourceManager.GetString("Error_Saving_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Sheet Name Empty!.
        /// </summary>
        internal static string Excel_Sheet_Name_Empty {
            get {
                return ResourceManager.GetString("Excel_Sheet_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate for .
        /// </summary>
        internal static string Exchange_rate_for {
            get {
                return ResourceManager.GetString("Exchange_rate_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate must be an number!.
        /// </summary>
        internal static string Exchange_Rate_must_be_an_number {
            get {
                return ResourceManager.GetString("Exchange_Rate_must_be_an_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Saved!.
        /// </summary>
        internal static string Failed_to_Saved {
            get {
                return ResourceManager.GetString("Failed_to_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty cannot be more than allocatable Qty.
        /// </summary>
        internal static string FrmAllocation_NewSave_Qty_cannot_be_more_than_allocatable_Qty {
            get {
                return ResourceManager.GetString("FrmAllocation_NewSave_Qty_cannot_be_more_than_allocatable_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate path : .
        /// </summary>
        internal static string FrmDbSetting_ButtonOkClick_Cannot_locate_path___ {
            get {
                return ResourceManager.GetString("FrmDbSetting_ButtonOkClick_Cannot_locate_path___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has been updated, and the application will now restart..
        /// </summary>
        internal static string FrmDbSetting_ButtonOkClick_The_database_has_been_updated__and_the_application_will_now_restart_ {
            get {
                return ResourceManager.GetString("FrmDbSetting_ButtonOkClick_The_database_has_been_updated__and_the_application_wil" +
                        "l_now_restart_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   .
        /// </summary>
        internal static string FrmMain_FrmMainLoad___________________ {
            get {
                return ResourceManager.GetString("FrmMain_FrmMainLoad___________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               * New version .
        /// </summary>
        internal static string FrmMain_FrmMainLoad_________________New_version_ {
            get {
                return ResourceManager.GetString("FrmMain_FrmMainLoad_________________New_version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               Version:.
        /// </summary>
        internal static string FrmMain_FrmMainLoad_______________Version_ {
            get {
                return ResourceManager.GetString("FrmMain_FrmMainLoad_______________Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  available * .
        /// </summary>
        internal static string FrmMain_FrmMainLoad__available___ {
            get {
                return ResourceManager.GetString("FrmMain_FrmMainLoad__available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      .
        /// </summary>
        internal static string FrmMain_SwitchToLocalToolStripMenuItemClick______ {
            get {
                return ResourceManager.GetString("FrmMain_SwitchToLocalToolStripMenuItemClick______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID cannot be empty!.
        /// </summary>
        internal static string ID_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("ID_cannot_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an incorrect Username or password. Please try again!.
        /// </summary>
        internal static string iincorrect_Username_or_password {
            get {
                return ResourceManager.GetString("iincorrect_Username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an incorrect Username or password. Please login!.
        /// </summary>
        internal static string incorrect_login {
            get {
                return ResourceManager.GetString("incorrect_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an incorrect Username or password. Application will be exit!.
        /// </summary>
        internal static string incorrect_Username_or_password_Application_will_be_exit_ {
            get {
                return ResourceManager.GetString("incorrect_Username_or_password_Application_will_be_exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infromation.
        /// </summary>
        internal static string Infromation {
            get {
                return ResourceManager.GetString("Infromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local connection not setup!.
        /// </summary>
        internal static string Local_connection_not_setup {
            get {
                return ResourceManager.GetString("Local_connection_not_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local database setting not setup!.
        /// </summary>
        internal static string Local_database_setting_not_setup {
            get {
                return ResourceManager.GetString("Local_database_setting_not_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NEW.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock.
        /// </summary>
        internal static string New_Stock {
            get {
                return ResourceManager.GetString("New_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data!.
        /// </summary>
        internal static string No_Data {
            get {
                return ResourceManager.GetString("No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data!.
        /// </summary>
        internal static string No_Data_ {
            get {
                return ResourceManager.GetString("No_Data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Decimal allow!.
        /// </summary>
        internal static string No_Decimal_allow_ {
            get {
                return ResourceManager.GetString("No_Decimal_allow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office LAN connection not setup!.
        /// </summary>
        internal static string Office_LAN_connection_not_setup {
            get {
                return ResourceManager.GetString("Office_LAN_connection_not_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Address!.
        /// </summary>
        internal static string Please_enter_A_valid_Address {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Currency Code!.
        /// </summary>
        internal static string Please_enter_A_valid_Currency_Code {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Currency_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Customer Code NAME!.
        /// </summary>
        internal static string Please_enter_A_valid_Customer_Code_NAME {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Customer_Code_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Customer NAME!.
        /// </summary>
        internal static string Please_enter_A_valid_Customer_NAME {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Customer_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid email Address!.
        /// </summary>
        internal static string Please_enter_A_valid_email_Address {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Exchange Rate!.
        /// </summary>
        internal static string Please_enter_A_valid_Exchange_Rate {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Exchange_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Fax No.!.
        /// </summary>
        internal static string Please_enter_A_valid_Fax_No {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Fax_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid GST Value!.
        /// </summary>
        internal static string Please_enter_A_valid_GST_Value {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_GST_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid LOGIN NAME!.
        /// </summary>
        internal static string Please_enter_A_valid_LOGIN_NAME {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_LOGIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Role!.
        /// </summary>
        internal static string Please_enter_a_valid_Role {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid Tel No.!.
        /// </summary>
        internal static string Please_enter_A_valid_Tel_No {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_Tel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid User Level!.
        /// </summary>
        internal static string Please_enter_A_valid_User_Level {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_User_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter A valid USER NAME!.
        /// </summary>
        internal static string Please_enter_A_valid_USER_NAME {
            get {
                return ResourceManager.GetString("Please_enter_A_valid_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Cost!.
        /// </summary>
        internal static string Please_enter_Cost {
            get {
                return ResourceManager.GetString("Please_enter_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an valid Qty! Qty must be a whole number with no decimal point..
        /// </summary>
        internal static string Please_enter_Qty {
            get {
                return ResourceManager.GetString("Please_enter_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Stock Code!.
        /// </summary>
        internal static string Please_enter_Stock_Code {
            get {
                return ResourceManager.GetString("Please_enter_Stock_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Unit Price!.
        /// </summary>
        internal static string Please_enter_Unit_Price {
            get {
                return ResourceManager.GetString("Please_enter_Unit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category.
        /// </summary>
        internal static string Please_select_a_category {
            get {
                return ResourceManager.GetString("Please_select_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file first!.
        /// </summary>
        internal static string Please_select_a_file_first {
            get {
                return ResourceManager.GetString("Please_select_a_file_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Part No!.
        /// </summary>
        internal static string Please_select_a_Part_No {
            get {
                return ResourceManager.GetString("Please_select_a_Part_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select A valid Country!.
        /// </summary>
        internal static string Please_select_A_valid_Country {
            get {
                return ResourceManager.GetString("Please_select_A_valid_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select A valid Status!.
        /// </summary>
        internal static string Please_select_A_valid_Status {
            get {
                return ResourceManager.GetString("Please_select_A_valid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Valid Part Number!.
        /// </summary>
        internal static string Please_select_an_Valid_Part_Number {
            get {
                return ResourceManager.GetString("Please_select_an_Valid_Part_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Currency!.
        /// </summary>
        internal static string Please_select_Currency {
            get {
                return ResourceManager.GetString("Please_select_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group!.
        /// </summary>
        internal static string Please_Select_GRoup {
            get {
                return ResourceManager.GetString("Please_Select_GRoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select supplier!.
        /// </summary>
        internal static string Please_select_supplier {
            get {
                return ResourceManager.GetString("Please_select_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string Please_try_again {
            get {
                return ResourceManager.GetString("Please_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port cannot be empty.
        /// </summary>
        internal static string Port_cannot_be_empty {
            get {
                return ResourceManager.GetString("Port_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Received More Than Outstanding Quantity!.
        /// </summary>
        internal static string Quantity_Received_More_Than_Outstanding_Quantity {
            get {
                return ResourceManager.GetString("Quantity_Received_More_Than_Outstanding_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate received must be an number!.
        /// </summary>
        internal static string Rate_received_must_be_an_number {
            get {
                return ResourceManager.GetString("Rate_received_must_be_an_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exist! Do you wish to create another?.
        /// </summary>
        internal static string Record_already_exist__Do_you_wish_to_create_another_ {
            get {
                return ResourceManager.GetString("Record_already_exist__Do_you_wish_to_create_another_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Exported.
        /// </summary>
        internal static string Records_Exported {
            get {
                return ResourceManager.GetString("Records_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote connection not setup!.
        /// </summary>
        internal static string Remote_connection_not_setup_ {
            get {
                return ResourceManager.GetString("Remote_connection_not_setup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote database setting not setup!.
        /// </summary>
        internal static string Remote_database_setting_not_setup {
            get {
                return ResourceManager.GetString("Remote_database_setting_not_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Done!.
        /// </summary>
        internal static string Restore_Done {
            get {
                return ResourceManager.GetString("Restore_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string Save_Please_try_again {
            get {
                return ResourceManager.GetString("Save_Please_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a priority customer first.
        /// </summary>
        internal static string select_a_priority_customer_first {
            get {
                return ResourceManager.GetString("select_a_priority_customer_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text file.
        /// </summary>
        internal static string Select_a_text_file {
            get {
                return ResourceManager.GetString("Select_a_text_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string Select_xls_file {
            get {
                return ResourceManager.GetString("Select_xls_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xls files (*.xls;*.csv;*.txt)|*.xls;*.csv;*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string SelectOpenFile_xls_file {
            get {
                return ResourceManager.GetString("SelectOpenFile_xls_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv files (*.csv;*.xls;*.txt)|*.csv;*.xls;*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string SelectTextFile {
            get {
                return ResourceManager.GetString("SelectTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server cannot be empty.
        /// </summary>
        internal static string Server_cannot_be_empty {
            get {
                return ResourceManager.GetString("Server_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Active.
        /// </summary>
        internal static string Set_Active {
            get {
                return ResourceManager.GetString("Set_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has been updated and the application will now restart.
        /// </summary>
        internal static string The_database_has_been_updated__and_the_application_will_now_restart {
            get {
                return ResourceManager.GetString("The_database_has_been_updated__and_the_application_will_now_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed!.
        /// </summary>
        internal static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id cannot be empty.
        /// </summary>
        internal static string User_Id_cannot_be_empty {
            get {
                return ResourceManager.GetString("User_Id_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rights updated!.
        /// </summary>
        internal static string User_rights_updated_ {
            get {
                return ResourceManager.GetString("User_rights_updated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Upgrade.
        /// </summary>
        internal static string Version_Upgrade {
            get {
                return ResourceManager.GetString("Version_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using local database! Please switch to Office Lan or Remote connection!.
        /// </summary>
        internal static string You_are_using_local_database__Please_switch_to_Office_Lan_or_Remote_connection {
            get {
                return ResourceManager.GetString("You_are_using_local_database__Please_switch_to_Office_Lan_or_Remote_connection", resourceCulture);
            }
        }
    }
}
